# Generated by Django 5.0.3 on 2024-03-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen_bandera', models.ImageField(upload_to='banderas/')),
                ('escudo_equipo', models.ImageField(upload_to='escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('T', 'Técnico'), ('A', 'Asistente'), ('M', 'Médico'), ('P', 'Preparador Físico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('foto_jugador', models.ImageField(upload_to='jugadores/')),
                ('fecha_nacimiento', models.DateField()),
                ('numero_camiseta', models.IntegerField()),
                ('es_titular', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='fifapp.equipo')),
                ('posicion_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifapp.posicionjuego')),
            ],
        ),
    ]
