# Generated by Django 5.0.3 on 2024-03-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='foto_jugador',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='posicion_juego',
            new_name='posicion',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='es_titular',
            new_name='titular',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifapp.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='rol',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Asistente', 'Asistente'), ('Médico', 'Médico'), ('Preparador Físico', 'Preparador Físico')], max_length=20),
        ),
    ]
