# Generated by Django 5.0.3 on 2024-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifapp', '0003_alter_tecnico_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
    ]
